"""adding scanned_file_name and received_file_name and original_file name

Revision ID: 0ec88ced44f0
Revises: 24d96298fe27
Create Date: 2026-03-06 14:36:03.890823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec88ced44f0'
down_revision: Union[str, Sequence[str], None] = '24d96298fe27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('original_file_name', sa.String(), nullable=False))
    op.add_column('scans', sa.Column('scanned_file_name', sa.String(), nullable=False))
    op.drop_column('scans', 'storage_file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('storage_file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('scans', 'scanned_file_name')
    op.drop_column('scans', 'original_file_name')
    # ### end Alembic commands ###
