"""adding storage file name on scans table

Revision ID: 24d96298fe27
Revises: 86dcbfdc7908
Create Date: 2026-03-06 11:18:41.525530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d96298fe27'
down_revision: Union[str, Sequence[str], None] = '86dcbfdc7908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('storage_file_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'storage_file_name')
    # ### end Alembic commands ###
